name: Add Git Trailers to PR commits

on:
  workflow_call:
    secrets:
      GIT_CLONE_PAT:
        required: false
      URUNC_BOT_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  git-trailers:
    name: Add Git Trailers
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
    continue-on-error: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Exit if PR is not rebaseable
        if: ${{ github.event.pull_request.rebaseable != null && github.event.pull_request.rebaseable == false }}
        run: exit 1

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Append git trailers
        uses: nubificus/git-trailers@8e08c91bb4c1fd9cb1ccbd9cc8029c31acf8da66 # feat_use_rebase
        with:
          user_info: .github/contributors.yaml

      - name: Generate urunc-bot token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.URUNC_BOT_APP_ID }}
          private-key: ${{ secrets.URUNC_BOT_PRIVATE_KEY }}

      - name: Set up Git
        run: |
          git config --global user.name "urunc-bot[bot]"
          git config --global user.email "urunc-bot[bot]@users.noreply.github.com"

      - name: Append git trailers
        uses: nubificus/git-trailers@0db3a5a7c2d42933ca079cbd5b9919680ce1d869 # fix_auto_merge
        with:
          user_info: .github/contributors.yaml

      - name: Merge PR
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          PR_URL=${{ github.event.pull_request.html_url }}
      
          gh pr merge "$PR_URL" --rebase --admin
