name: Build & Upload

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.sha }}
      go_version: "1.26.4"

  release:
    name: Rolling release
    needs: build
    permissions:
      contents: write
    uses: ./.github/workflows/rolling_release.yml
    with:
      ref: ${{ github.sha }}
      tag: nightly

