name: Final merge to main

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main-pr*'

permissions:
  contents: read

jobs:
  add-trailers-and-merge:
    if: |
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Exit if PR is not rebaseable
        if: ${{ github.event.pull_request.rebaseable != null && github.event.pull_request.rebaseable == false }}
        run: exit 1

      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Generate urunc-bot token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ vars.URUNC_BOT_APP_ID }}
          private-key: ${{ secrets.URUNC_BOT_PRIVATE_KEY }}

      - name: Append git trailers
        uses: nubificus/git-trailers@9bf4235762fb658e76ce9858fbb97b01ba9f33b8
        with:
          user_info: .github/contributors.yaml
          rebase_branch: ${{ github.event.pull_request.base.ref }}


      - name: Create a Pull Request from PR_BRANCH to main and merge it
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          PR_BRANCH=${{ github.event.pull_request.base.ref }}

          # Create the pull request
          PR_URL=$(gh pr create \
            --head "$PR_BRANCH" \
            --base main \
            --title "Merge External PR: Merge $PR_BRANCH into main" \
            --body "This PR was automatically created by GitHub Actions to merge changes from $PR_BRANCH into main.")

          gh pr merge "$PR_URL" --rebase --admin --delete-branch
